# Generated by Django 3.0.7 on 2021-02-24 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210224_1111'),
    ]

    operations = [
        migrations.CreateModel(
            name='employ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=225)),
                ('cmobile_no', models.CharField(max_length=225)),
                ('cemail', models.EmailField(max_length=225)),
                ('cjob', models.CharField(max_length=225)),
            ],
        ),
    ]
