# Generated by Django 3.0.7 on 2021-02-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employ',
            old_name='cemail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employ',
            old_name='cjob',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='employ',
            old_name='cmobile_no',
            new_name='mobile_no',
        ),
        migrations.RenameField(
            model_name='employ',
            old_name='cname',
            new_name='name',
        ),
    ]
