# Generated by Django 3.0.7 on 2021-03-01 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210224_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employ',
            old_name='job',
            new_name='course',
        ),
    ]
